using System.Collections.Generic;
using UnityEngine;

namespace MoveIt.Furniture
{
    /// <summary>
    /// List of every placeable furniture prefab. Generated by MoveIt > Furniture > Build Prefabs,
    /// so the selector UI can be filled from one asset instead of a hand-maintained list.
    /// </summary>
    [CreateAssetMenu(fileName = "FurnitureCatalog", menuName = "MoveIt/Furniture Catalog")]
    public class FurnitureCatalog : ScriptableObject
    {
        [SerializeField]
        List<FurnitureItem> m_Items = new List<FurnitureItem>();

        /// <summary>
        /// All furniture prefabs, ordered by category and then name.
        /// </summary>
        public IReadOnlyList<FurnitureItem> items => m_Items;

        /// <summary>
        /// Returns the prefabs in the given category.
        /// </summary>
        public IEnumerable<FurnitureItem> GetByCategory(string category)
        {
            foreach (var item in m_Items)
            {
                if (item != null && item.category == category)
                    yield return item;
            }
        }

        /// <summary>
        /// Returns the prefab with the given id, or null.
        /// </summary>
        public FurnitureItem GetById(string id)
        {
            foreach (var item in m_Items)
            {
                if (item != null && item.id == id)
                    return item;
            }

            return null;
        }

        /// <summary>
        /// Replaces the catalog contents. Called by the editor prefab builder.
        /// </summary>
        public void SetItems(List<FurnitureItem> items)
        {
            m_Items = items;
        }
    }
}
